### ISSUE TITLE
comentario

### ISSUE THREAD

**Issue by JhonCodeU** [JhonF424/VentaCelulares2.0#1]
Porque creastes dos proyectos si pudieras crear dos ramas

**Comment by JhonF424** [comment]
Saludos, recién estoy aprendiendo GIT por mi cuenta. Lo estoy usando para respaldar los proyectos que hago en la universidad, hasta el momento solo he aprendido lo básico de hacer commit, push y pull, aún no aprendo a hacer branches, merge, etc

**Comment by JhonCodeU** [comment]
Buena suerte aprendiendo git
